concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "uzmos-runner"
  url = "https://gitlab.com/"
  id = 17179811
  token = "VuYiAFqWvo-dd-76iAE6"
  token_obtained_at = 2022-08-26T08:49:35Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]

[[runners]]
  name = "uzmos-runner2"
  url = "https://gitlab.com/"
  id = 17180290
  token = "EQEWP1aza5h3DZZPUGnf"
  token_obtained_at = 2022-08-26T09:30:34Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
