export enum MAIN_SCREENS {
  empty = "empty",
  home = "home",
  customerProfile = "customerProfile",
  serviceDetail = "serviceDetail",
  categoryDetail = "categoryDetail",
  staffProfile = "staffProfile",
  categoryProfile = "categoryProfile",
  newAppointment = "newAppointment",
  productDetail = "productDetail",
  workingDays = "workingDays",
  catagoryProfile = "catagoryProfile",
  breaks = "breaks",
  timeOff = "timeOff",
  timeOffDetail = "timeOffDetail",
  companyHours = "companyHours",
  timeZone = "timeZone",
  storeDetail = "storeDetail",
  bookingPolicies = "bookingPolicies",
  bookingSlotSize = "bookingSlotSize",
  customerNotes = "customerNotes",
  cancellationPolicy = "cancellationPolicy",
  appointmentSlot = "appointmentSlot",
  weekStartDay = "weekStartDay",
  newLabel = "newLabel",
  appointmentDetail = "appointmentDetail",
  editAppointment = "editAppointment",
  additionSelect = "additionSelect",
  serviceList = "serviceList",
  categoryList = "categoryList",
  customerList = "customerList",
  newService = "newService",
  newCategory = "newCategory",
  staffList = "staffList",
  productList = "productList",
  customerImport = "customerImport",
  settings = "settings",
  labelList = "labelList",
  checkout = "checkout",
  packageList = "packageList",
  newPackage = "newPackage",
  packageDetail = "packageDetail",
  editPackage = "editPackage",
  privacy = "privacy",
  cancelAppointment = "cancelAppointment",
  storeMenu = "storeMenu",
  editAccount = "editAccount",
  accountProfile = "accountProfile",
  changePassword = "changePassword",
  paymentType = "paymentType",
  cashPayment = "cashPayment",
  cardPayment = "cardPayment",
  otherPayment = "otherPayment",
  editService = "editService",
  taxList = "taxList",
  newTax = "newTax",
  searchLocation = "",
  taxDetail = "Tax detail",
  editTax = "Edit tax",
  discountList = "discountList",
  newDiscount = "newDiscount",
  discountDetail = "discountDetail",
  editDiscount = "editDiscount",
}

export enum AUTH_SCREENS {
  onboarding = "onboarding",
  signIn = "signIn",
  signUp = "signUp",
  forgotPassword = "forgotPassword",
  storeForm = "storeForm",
  companyHours = "companyHours",
  timeZone = "timeZone",
  modal = "modal",
  login = "login",
  test = "test",
  global = "global",
  empty = "empty",
}

export enum COMMON_SCREENS {
  searchLocation = "searchLocation",
}
